### ISSUE TITLE
Add ICollection extensions for better performance

### ISSUE THREAD

**Issue by aalmada** [feO2x/Light.GuardClauses#44]
Operations on **IEnumerable** can only be performed by iterating through each item. For example, Count() goes through the whole collection to get its count.
**ICollection** contains a **Count** property and a **Contains** method. A CollectionAssertions.cs with guard clauses that call these is much more efficient for collections that implement this interface.

**Comment by feO2x** [comment]
@aalmada Thanks for your feedback. I'm not that big of a fan of the `IEnumerable<T>` interface either, but a lot of other code uses this interface to access collections - and that's why I initially used this interface for collection assertions, too.

As you can see e.g. [here](https://github.com/feO2x/Light.GuardClauses/blob/2e08b313cc779f734fee383b5e51894f80ac9589/Code/Light.GuardClauses/EnumerableAssertions.cs#L235), I usually try to downcast an `IEnumerable<T>` to an `IReadOnlyList<T>`  within assertion methods (using the `AsReadOnlyList` extension method which returns a new list with the enumerable's instances when the latter cannot be casted). This allows me to use the Count property and not using foreach loops (and thus avoid enumerator allocation, etc.).

I know it's not the optimal way of doing things because in some circumstances, I'll create a new List<T> this way when e.g. a `Dictionary<TKey, TValue>.KeyCollection` instance is passed which does not implement `IReadOnlyList<T>`.

We could tackle this problem in several ways:

1. Provide extension methods for additional collection interfaces (namely `ICollection<T>`, `IList<T>`, `IReadOnlyCollection<T>`, and `IReadOnlyList<T>`)
2. Use a more sophisticated algorithm to perform a single collection assertion, i.e. if the passed in collection is implementing one of the interfaces mentioned at 1., then use a for loop, otherwise use a foreach loop.

Both solutions complicate the internal design a bit, but I think option 1 is better when we incorporate something like T4 templates or other frameworks that create the implementations for different collection interfaces.

Did you perform any profiling / benchmarks that showed a significant performance issue? What's your opinion on the two solutions above? Do you have something different in mind?

**Comment by feO2x** [comment]
I've made some [performance tests for loops](https://github.com/feO2x/Light.GuardClauses/blob/dcf58ca8bd6f175ad732c7e626ed206ab104674f/Code/Light.GuardClauses.Performance/Results/2017-12-17-LoopCheck-Desktop.log#L10582) in general and for [`IsSubSetOf` in particular](https://github.com/feO2x/Light.GuardClauses/blob/dcf58ca8bd6f175ad732c7e626ed206ab104674f/Code/Light.GuardClauses.Performance/Results/2017-12-24-IsSubSetOfPerformance-SurfacePro4.log#L1789) to get a feeling about the performance of collection assertions. The result is the following:

- iterating arrays is fastest (`for` or `foreach` loop are equally fast, no allocations)
- iterating `List<T>` is 4 times slower than iterating arrays (again, `for` and `foreach` loop are equally fast)
- iterating `IReadOnlyList<T>` via a for loop is 9 times slower than using an array
- iterating `IEnumerable<T>` with a `foreach` loop is 12 times slower than using an array (and this also allocates 40 bytes for the `IEnumerator<T>`)

Anyway, one only gets into trouble when iterating over more than 1.000 items, in any other case the difference is up to 2ms between the different ways to access a collection. (How often do you have collections with more than 1.000 items? It's not that often in my daily coding scenarios...) What we should do with this knowledge is providing several overloads for every collection assertion that takes arrays, `List<T>`, `IReadOnlyList<T>`, and `IEnumerable<T>`, which increases the complexity the code a lot. I'm currently looking into [Scripty](https://github.com/daveaglick/Scripty/tree/master) to auto-generate the overloads for the different types.

@aalmada Did you profile your applications and do you have something to add to this?

**Comment by feO2x** [comment]
In version 4.0.0, all assertions on collections do not allocate and are way faster than in 3.5. I'll publish my benchmark results in the next few days. 69ab020e8c609022c73f6ff2824833fb7b32e90a
